name: Smhi_weather

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger with parameters
    inputs:
      log_errors:
        description: 'Log errors if tests fail'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify tests directory
        run: ls -la  # Lists files and confirms 'tests' directory presence in the root

      - name: Run unit tests
        run: python -m unittest discover -s tests

  dockerhub:
    runs-on: ubuntu-latest
    needs: test  # Ensures 'dockerhub' job runs after 'test' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weatherapp:latest .

      - name: Build Docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/weatherapp:latest .
        
