name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger with parameters
    inputs:
      log_errors:
        description: 'Log errors if tests fail'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests

  build-and-publish:
    needs: test  # Runs only if the 'test' job passes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.log_errors == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t arees313/flask-app:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish Docker image
        run: docker push Arees313/flask-app:latest

  deploy:
    needs: build-and-publish  # Runs only if 'build-and-publish' job passes
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure
        env:
          AZURE_WEBAPP_NAME: your-app-name
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          # Deploy Docker image to Azure App Service
          az webapp config container set --name $AZURE_WEBAPP_NAME --resource-group your-resource-group --docker-custom-image-name yourusername/flask-app:latest
