name: Smhi_weather

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger with parameters
    inputs:
      log_errors:
        description: 'Log errors if tests fail'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify tests directory
        run: ls -la  # Lists files and confirms 'tests' directory presence in the root

      - name: Run unit tests
        run: python -m unittest discover -s tests

      # Upload error log if tests fail and `log_errors` is true-
      - name: Log errors if tests fail (only if `log_errors == 'true'`)
        if: ${{ github.event.inputs.log_errors == 'true' && failure() }}
        run: |
          echo "Test failed, generating error log" > error_log.txt
          echo "Error details: $(cat error_log.txt)"
          echo "Uploading error log"
          # Upload error log artifact
          echo "Error log uploaded"

      # Upload artifact step, only if `log_errors == 'true'`
      - name: Upload error log artifact
        if: ${{ github.event.inputs.log_errors == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: error_log.txt

  dockerhub:
    runs-on: ubuntu-latest
    needs: test  # Ensures 'dockerhub' job runs after 'test' job
    if: ${{ success() }}  # Ensures this job only runs if the 'test' job was successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weatherapp:latest .
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/weatherapp:latest

